### ISSUE TITLE
Sort Feature Request

### ISSUE THREAD

**Issue by JackWall63** [micahlt/offsides#1]
It would be really nice if the app saved my sort preferences. Personally, I always sort by new, so it would be nice to have it do that automatically if I set it to last time.

**Comment by micahlt** [comment]
Excellent!  I'll work on this soon.

**Comment by JackWall63** [comment]
![Screenshot 2024-04-03 232551](https://github.com/micahlt/offsides/assets/123191287/ebad31d8-0aef-49e4-8bf5-28aa6bdbb2f8)

I like to sort by new. It would be nice to have it scroll indefinitely. Also, currently, at the bottom of new, the post button blocks the voting buttons

**Comment by micahlt** [comment]
This is being worked on!

**Comment by micahlt** [comment]
This was partially added in [0.6.2](https://github.com/micahlt/offsides/releases/tag/0.6.2).  Still working on moving the post button, but sorting should work and be persistent.

**Comment by JackWall63** [comment]
Sorting is persistent, thank you!

**Comment by micahlt** [comment]
I've moved the post button problem to a separate issue, feel free to track it: #7
