### ISSUE TITLE
Upon opening, nothing loads until a post is made.

### ISSUE THREAD

**Issue by Ramen-Man-taken** [micahlt/offsides#10]
Just as stated. Samsung s21u, last and current app updates, newest Samsung update.
![Screenshot_20240421_010328_Offsides](https://github.com/micahlt/offsides/assets/167499706/d0ccf721-81a2-4b46-b5d1-82f44013943f)

**Comment by micahlt** [comment]
Merging this with issue #11 .

**Comment by Ramen-Man-taken** [comment]
They're essentially the same anyway.
