### ISSUE TITLE
Black screen when opening app

### ISSUE THREAD

**Issue by JackWall63** [micahlt/offsides#11]
![Screenshot_20240429_181455_Offsides](https://github.com/micahlt/offsides/assets/123191287/cf70c8d5-f23e-4a83-9b89-855899ae4070)

About 40% of the time I open the app I get this. I must click to sort and set it to recent.

**Comment by JackWall63** [comment]
> Are you coming across this error still?

I have not used the app a ton since summer started, however since the update I have not run into the issue. I will post a new issue if it happens again.

**Comment by micahlt** [comment]
Sounds good.  For now I will close this and if you encounter it again let me know and I'll reopen it.
