### ISSUE TITLE
Failure to load on launch

### ISSUE THREAD

**Issue by JackWall63** [micahlt/offsides#14]
![Screenshot_20240708_192552_Offsides](https://github.com/micahlt/offsides/assets/123191287/d4ea77da-7580-4ec1-a690-ebf9ce4f4da9)

I still having this issue when I open the app occasionally.

**Comment by Jeev1234567** [comment]
You need to click on the button with the 3 lines next to your profile and select new or hot posts

**Comment by JackWall63** [comment]
> You need to click on the button with the 3 lines next to your profile and select new or hot posts

Sometimes it will automatically start on new and sometimes it will just be blank like that and require me to press new. It would be nice to automatically be on the last one I left it on.

**Comment by micahlt** [comment]
I'm aware of this issue and am working on a fix!

**Comment by micahlt** [comment]
I've got a fix prepped for this one - should be releasing sometime tomorrow hopefully.
