### ISSUE TITLE
Handling Erroneous Usernames

### ISSUE THREAD

**Issue by JackWall63** [micahlt/offsides#15]
When changing a username, the user should be told why they can't use a specific username. Telling them they are now allowed to use capitalizations or spaces, for example.

**Comment by micahlt** [comment]
This is a cool idea, but it's out of the scope of Offsides because all the Sidechat API gives me is a true or false statement of the username's validity.  Anything more than that would just be a guess, and also a feature that to my knowledge isn't supported in the official Sidechat app.
