### ISSUE TITLE
Links are not properly shown

### ISSUE THREAD

**Issue by Jeev1234567** [micahlt/offsides#16]
When someone sends a link, the message shown is just a blank box. Images are what is displayed in Yikesforweb vs what is displayed in Offsides 
![Screenshot_20240727-220358](https://github.com/user-attachments/assets/a55fc816-b202-4363-ae0e-d483270bcae2)
![Screenshot_20240727-220309](https://github.com/user-attachments/assets/bf2b8a28-dcd7-46dd-902c-062b1c08dc7a)

**Comment by micahlt** [comment]
Interesting - is there a public community you could point me to that has an example of this?

**Comment by Jeev1234567** [comment]
Yeah theres an example in the YouTube community. Here is what is looks like: 
![Screenshot_20240806-162110](https://github.com/user-attachments/assets/dbc5a8c6-6e8b-4af9-8ea7-9a7df412d3c3)
![Screenshot_20240806-162114](https://github.com/user-attachments/assets/ce28435e-22fe-4df3-9081-09f617ef354e)

**Comment by micahlt** [comment]
This was added in 7da7e829075d5e4e7e1635fbec40ed370a3ea748.  It will be released in the next update.
