### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Ramen-Man-taken** [micahlt/offsides#19]
After app data wipe, reinstall, logging in again, etc. I have to report that my app keeps crashing. Giving a grey screen and closing every time the app loads. If I change filters or scroll to the end of a page, crashing, crashing, crashing.

Samsung 21U 5G

**Comment by Monstergamester** [comment]
Im also having the same issue. For a band-aid fix, version 0.7.0 works for me

**Comment by micahlt** [comment]
> After app data wipe, reinstall, logging in again, etc. I have to report that my app keeps crashing. Giving a grey screen and closing every time the app loads. If I change filters or scroll to the end of a page, crashing, crashing, crashing.
> 
> Samsung 21U 5G

I'm tracking this issue and I'm aware of it, expect a new release very soon!

**Comment by Monstergamester** [comment]
Im not encountering the issue anymore

**Comment by micahlt** [comment]
Closing this for now since it should be resolved in version 0.7.2.
