### ISSUE TITLE
Long Commenters' Names Squeezes the Time Stamp

### ISSUE THREAD

**Issue by JackWall63** [micahlt/offsides#2]
![image](https://github.com/micahlt/offsides/assets/123191287/d4dfc0a4-d86a-4b51-a517-ec72ee9f4c34)

**Comment by micahlt** [comment]
Which would you prefer to see, the username or the timestamp?

**Comment by JackWall63** [comment]
Could you life the username up to the start of the profile picture and in small text have the time stamp underneath? Perhaps it does this only if the username is a certain length and otherwise stays as is?

**Comment by micahlt** [comment]
Excellent idea!

**Comment by micahlt** [comment]
Can you check the latest version of the app and see if it fixes your request?

**Comment by micahlt** [comment]
Awesome!  Until then I'll close this issue.
