### ISSUE TITLE
Dms broken 

### ISSUE THREAD

**Issue by joemoma21** [micahlt/offsides#23]
Can't view dms just shows a blank grey screen 

/

**Comment by joemoma21** [comment]
Just to update this going to previous versions doesn't fix the issue

**Comment by joemoma21** [comment]
Still broken in the 0.7.3 update

**Comment by micahlt** [comment]
Have you started any DMs?  I'm not seeing any reported crashes.

**Comment by joemoma21** [comment]
Yes whenever I try to look at my dms it loads for a little bit then the
screen goes grey

**Comment by micahlt** [comment]
I am not able to replicate this on my end and there are no logs of a crash.  Unless I receive a crash report or more info then I will not be able to diagnose this issue.

**Comment by joemoma21** [comment]
> I am not able to replicate this on my end and there are no logs of a crash. Unless I receive a crash report or more info then I will not be able to diagnose this issue.

I just got the app to crash while trying to look at my dms

**Comment by joemoma21** [comment]
You should have a couple crash reports now

**Comment by micahlt** [comment]
I believe that I got it fixed!  Please download the latest version of the app.

**Comment by joemoma21** [comment]
Yeah they are working now
