### ISSUE TITLE
"Verify Your Age" text box is really tall

### ISSUE THREAD

**Issue by TheGitHub428Guy** [micahlt/offsides#25]
Self explanatory; the box to enter your age is so tall that the button to proceed is off-screen.
This problem exists in 0.7.3 but not 0.7.2, and I think it might've appeared in https://github.com/micahlt/offsides/commit/2c1423fbb2fa221fd0e95405a84b51a7899a2342.
![image](https://github.com/user-attachments/assets/cc7ce31c-8f95-431a-adcf-3d0fdc7af12a)

**Comment by micahlt** [comment]
This issue was resolved in [release 0.7.4](https://github.com/micahlt/offsides/releases/tag/0.7.4).
