### ISSUE TITLE
Sidechat API Origin

### ISSUE THREAD

**Issue by WarpWing** [micahlt/offsides#27]
Hi, I was wondering how exactly you're using the sidechat API, is there any documentation, I just wanted to make a CLI version for fun and was wondering how exactly you're interacting with the API. Thanks!

**Comment by micahlt** [comment]
Yes!  There's an entire JS client that I've written for use in other projects. 
https://www.npmjs.com/package/sidechat.js
https://github.com/micahlt/sidechat.js
