### ISSUE TITLE
Commenting Consequence

### ISSUE THREAD

**Issue by segasaur** [micahlt/offsides#28]
Hello, very cool app!! However, one issue I've run into is that when I comment (specifically reply to other's comments, I haven't tried posting an original yet) the comment posts and everything functions correctly...but when I restart the app, it kind of breaks. No more posts appear, and although I can select the buttons and see my profile/comments/etc, I can no longer see other's comments. I can, however, see that my reply has had more upvotes, so that must be functioning. Tried force stop and updating the app etc.
The first time this happened, I just deleted my replies and restarted the app and it functioned normally again.
Pics are the home screen and profile/comments screen during the bug. No clue what's happening but I appreciate everything you've done regardless 🫶

![Screenshot_20240918_221602_Offsides](https://github.com/user-attachments/assets/1fc53f21-a403-4e77-bff6-f0c5c7a3aee5)
![Screenshot_20240918_221620_Offsides](https://github.com/user-attachments/assets/6f81129c-f9ff-410f-b480-bb8914fd47bd)

**Comment by Jeev1234567** [comment]
You gotta click on the button next to your profile button and select one of the options.

**Comment by micahlt** [comment]
As @Jeev1234567 said, on the home screen click the Filter button (the three lines next to your profile button) and selecting something.
