### ISSUE TITLE
Reply doesn't work

### ISSUE THREAD

**Issue by JackWall63** [micahlt/offsides#3]
I can comment on a post, but when I reply to a comment, it doesn't actually reply. It shows that it works, but nothing is posted.

**Comment by micahlt** [comment]
I haven't had this issue, but I'll take a look!  Out of curiosity, is your Home group selected?

**Comment by JackWall63** [comment]
I was in the group that I was replying in.

**Comment by micahlt** [comment]
Okay, awesome.  I'll take a look

**Comment by JackWall63** [comment]
This seems to be working for me now.
