### ISSUE TITLE
Cant make a username

### ISSUE THREAD

**Issue by JungshookTacos97** [micahlt/offsides#31]
Everytime I put something as my username it tells me I can't use that as my username

**Comment by micahlt** [comment]
I just tested this and from my end it's working fine.  Try a longer username, or one with no special characters or curse words.

**Comment by JungshookTacos97** [comment]
Hi sorry I never got back to you, I'm still having this issue even with the newest update. No matter how long how unique I make it I cant make a username. Even with no special characters
![Screenshot_20241229-141521_Offsides](https://github.com/user-attachments/assets/bc6c92d0-566a-432a-ae59-ac9b328f1084)
Here's an example. I've tried numbers too and nothing

**Comment by tcofer19** [comment]
I am also having the same issue
