### ISSUE TITLE
No clue if I was banned

### ISSUE THREAD

**Issue by Ramen-Man-taken** [micahlt/offsides#32]
Recently as in the past few days I have been completely unable to comment. Unsure if I was banned but the app is still useable as far as upvotes or downvotes.

**Comment by micahlt** [comment]
What do you mean by "unable to comment"?  Errors, etc?

**Comment by Ramen-Man-taken** [comment]
I comment or post, it loads but never shows up.

**Comment by micahlt** [comment]
It sounds like you're probably banned.  You can also try logging out and in again.

**Comment by micahlt** [comment]
Closing this since it hasn't had any updates or follow-ups in a while.
