### ISSUE TITLE
As of the latest update, you can't switch groups or explore new groups

### ISSUE THREAD

**Issue by Jeev1234567** [micahlt/offsides#36]
Title basically explains the issue, tried switching groups on the latest update, it shows the animation of me tapping on the group, but the group does not load up.

**Comment by micahlt** [comment]
Just saw this, thanks for the report.  This is a pretty severe problem, can confirm it's happening on my end too.  Until I can get a fix rolled out, please switch back to the last release that was working for you!

**Comment by micahlt** [comment]
This is likely related to the switch to New Architecture.  I'll take a look this afternoon.

**Comment by micahlt** [comment]
@Jeev1234567 This issue was fixed in the latest release.  Please update as soon as possible!

**Comment by micahlt** [comment]
Scratch that -- it's still broken.  Not sure why.  Taking a look now.

**Comment by micahlt** [comment]
Okay, finally got this fixed.  The [latest update](https://github.com/micahlt/offsides/releases/latest) also has some great new features, so please update as soon as you can.

cc: @Jeev1234567
