### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by aekiraq** [micahlt/offsides#37]
0.7.8 update caused the app to no longer load at all, downgrading to previous version fixed the issue but it happened on mine and my boyfriend's device. forgot to take a screenshot but it was just a plain grey screen with no buttons

**Comment by micahlt** [comment]
Can you update to [0.7.9](https://github.com/micahlt/offsides/releases/tag/0.7.9) and see if that fixes the issue?

**Comment by aekiraq** [comment]
just updating from 0.7.7 to 0.7.9 did not work, but a full uninstall and reinstall with the 0.7.9 version fixed it!

**Comment by micahlt** [comment]
Wonderful!  Thank you.  I'm working on a fix for this issue right now.
