### ISSUE TITLE
Can't comment anonymously

### ISSUE THREAD

**Issue by HauntedBunnies** [micahlt/offsides#39]
Hello, huge thanks for this app! I was a bit worried about losing Sidechat when I switched to Android but this app works surprisingly well!

However, I've tried to comment on a post and, both with the anonymous logo on and crossed out, it comments with my username. I'm not sure if this is only client side, but it seems like either way, it comments with my username. Creating a post works as expected, though.

EDIT: I'm using 0.7.9

**Comment by micahlt** [comment]
Noted!  I'll take a look.  Thank you for the report.

**Comment by micahlt** [comment]
Will you please download the [latest release](https://github.com/micahlt/offsides/releases/latest) and see if this issue is resolved?

**Comment by HauntedBunnies** [comment]
Yup, just tried it and it works as expected! Thanks!

**Comment by micahlt** [comment]
Wonderful!  Thanks for using Offsides!
