### ISSUE TITLE
Cannot Delete Comment

### ISSUE THREAD

**Issue by JackWall63** [micahlt/offsides#4]
When clicking the delete button by a comment I posted, the app crashes and the comment is not deleted (Samsung s12 Ultra).

**Comment by micahlt** [comment]
This issue was fixed in [0.6.2](https://github.com/micahlt/offsides/releases/tag/0.6.2).  Please confirm that this works!

**Comment by JackWall63** [comment]
Worked for me on [0.6.2](https://github.com/micahlt/offsides/releases/tag/0.6.2)!
