### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by JackWall63** [micahlt/offsides#6]
I don't know if just using their API let's you do this, but notifications would be super helpful. Ideally for: comments on posts, replies, other comments on a post you commented on, # of upvotes called for a notif every 5 maybe, perhaps a way to subscribe to a post so you can receive notifications about that post without commenting on it yourself (like what reddit has).

**Comment by micahlt** [comment]
Sadly no, I can't access the notification API for multiple reasons.  I also can't just run my own notification server because that would mean storing other users' tokens on my hardware which I'm not willing to do for security reasons.

**Comment by JackWall63** [comment]
Yup, that makes sense, no worries.
