### ISSUE TITLE
New post button hides last post content

### ISSUE THREAD

**Issue by micahlt** [micahlt/offsides#7]
![image](https://github.com/micahlt/offsides/assets/28816297/3a706d0d-8a89-44a2-bdd5-b60b3e518b4e)

**Comment by micahlt** [comment]
@JackWall63 this was fixed in c5ea833c7bedd06a59598a2fdf898a6a1ebc143f (release 0.6.3) - please update!

**Comment by JackWall63** [comment]
> @JackWall63 this was fixed in [c5ea833](https://github.com/micahlt/offsides/commit/c5ea833c7bedd06a59598a2fdf898a6a1ebc143f) (release 0.6.3) - please update!

Wonderful, just did and it looks great!
