### ISSUE TITLE
Replying to replies

### ISSUE THREAD

**Issue by JackWall63** [micahlt/offsides#8]
I am unable to reply to replies: 

Uploading Screen_Recording_20240412_235500_Offsides.mp4…

**Comment by JackWall63** [comment]
Uploading Screen_Recording_20240412_235500_Offsides.mp4…

**Comment by micahlt** [comment]
Just a heads up, your video didn't upload correctly.  However, that's fine - I've already been able to replicate this.  Working on it!

**Comment by micahlt** [comment]
Turns out this is quite difficult to accomplish, and I'm still not sure how to do it.  I'll need to further reverse engineer the API to do this.

**Comment by JackWall63** [comment]
Interesting, great work! Do you have any other features planned?

**Comment by Jeev1234567** [comment]
If it's any help, yikesforweb has functionality for replies to comments, it could be a start to ask them how they did it!

**Comment by micahlt** [comment]
I've tried to talk to the YikesForWeb team before and they haven't been super receptive sadly :(

**Comment by Jeev1234567** [comment]
Hey, I've just downloaded the latest version and I've realized this works sometimes. It seems random though. Sometimes my reply to a reply gets posted as a new comment, but sometimes it gets posted as a reply to the comment.

**Comment by micahlt** [comment]
This was resolved in the latest release of the app (0.7.6).  Please update to that release to have this issue fixed!

cc: @JungshookTacos97 @CfopGod
